name: Scheduled Build
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      url1: 'https://api.github.com/repos/LACMTA/uptime/commits?path=/history/metro-api.yml'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Feed
        run: |-
          curl "[url1]" | jq . > output_file.json

      - name: Commit and push changes
        run: |-
          git diff
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git diff --quiet || (git add -A && git commit -m "Updated with latest")
          git push
